FROM alpine:3.15

ENV LC_ALL=ja_JP.UTF-8
ENV LANG=ja_JP.UTF-8
ENV LANGUAGE=ja_JP:ja
ENV TZ=Asia/Tokyo

COPY Pipfile /var/pipenv-lock-creator/
COPY pipenv-lock-create.sh /var/pipenv-lock-creator/pipenv-lock-create.sh

#追加必要であれば任意に追加すべし
RUN apk add --no-cache\
        python3 \
        py3-pip \
        mariadb-dev \
    && pip3 install pipenv --ignore-installed

WORKDIR /var/pipenv-lock-creator/

CMD ["ash","./pipenv-lock-create.sh"]
